// jwt
exports.DRECT_JWT = {
    JWT_SECRET: "U2FsdGVkX197tVlweepMwI9TGCZFBawTPXaio8WKmuTQWYOxQxQoYrBOlDt46JB5",
    JWT_ACCESS_EXPIRATION_MINUTES: 180,
    JWT_REFRESH_EXPIRATION_MINUTES: 180,
    JWT_RESET_PASSWORD_EXPIRATION_MINUTES: 10,
    JWT_RESET_PATTERN_EXPIRATION_MINUTES: 10,
    JWT_REFRESH_EXPIRATION_DAYS: 10,
    JWT_VERIFY_EMAIL_EXPIRATION_MINUTES: 10,
    JWT_SECURITY_VERIFY_MINUTES:10
}
